import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { activateRoutine, addRoutineDay, archiveRoutine, createRoutine, deactivateRoutine, duplicateRoutine, duplicateRoutineDay, getRoutine, getRoutines, removeRoutineExercise, renameRoutine, renameRoutineDay, reorderRoutineDays, reorderRoutineExercises, updateRoutineExercise } from '@/features/routines/api/routines';

export const routineKeys = { all: ['routines'] as const, detail: (id: string) => ['routines', id] as const };
export function useRoutines() { return useQuery({ queryKey: routineKeys.all, queryFn: getRoutines }); }
export function useRoutine(id: string) { return useQuery({ queryKey: routineKeys.detail(id), queryFn: () => getRoutine(id), enabled: Boolean(id) }); }
export function useCreateRoutine() { const client = useQueryClient(); return useMutation({ mutationFn: ({ userId, name }: { userId: string; name: string }) => createRoutine(userId, name), onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.all }) }); }
export function useAddRoutineDay(id: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ index, isRestDay }: { index: number; isRestDay: boolean }) => addRoutineDay(id, index, isRestDay), onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.detail(id) }) }); }
export function useActivateRoutine() { const client = useQueryClient(); return useMutation({ mutationFn: activateRoutine, onSuccess: (_, id) => Promise.all([client.invalidateQueries({ queryKey: routineKeys.all }), client.invalidateQueries({ queryKey: routineKeys.detail(id) }), client.invalidateQueries({ queryKey: ['today'] })]) }); }
export function useDeactivateRoutine() { const client = useQueryClient(); return useMutation({ mutationFn: deactivateRoutine, onSuccess: (_, id) => Promise.all([client.invalidateQueries({ queryKey: routineKeys.all }), client.invalidateQueries({ queryKey: routineKeys.detail(id) }), client.invalidateQueries({ queryKey: ['today'] })]) }); }
export function useArchiveRoutine() { const client = useQueryClient(); return useMutation({ mutationFn: archiveRoutine, onSuccess: (_, id) => Promise.all([client.invalidateQueries({ queryKey: routineKeys.all }), client.invalidateQueries({ queryKey: routineKeys.detail(id) }), client.invalidateQueries({ queryKey: ['today'] })]) }); }
export function useDuplicateRoutine(userId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (routine: Parameters<typeof duplicateRoutine>[0]) => duplicateRoutine(routine, userId), onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.all }) }); }
export function useUpdateRoutineExercise(routineId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, values }: { id: string; values: Parameters<typeof updateRoutineExercise>[1] }) => updateRoutineExercise(id, values), onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.detail(routineId) }) }); }
export function useRemoveRoutineExercise(routineId: string) { const client = useQueryClient(); return useMutation({ mutationFn: removeRoutineExercise, onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.detail(routineId) }) }); }
export function useDuplicateRoutineDay(routineId: string) { const client = useQueryClient(); return useMutation({ mutationFn: duplicateRoutineDay, onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.detail(routineId) }) }); }
export function useReorderRoutineExercises(routineId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ dayId, orderedIds }: { dayId: string; orderedIds: string[] }) => reorderRoutineExercises(dayId, orderedIds), onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.detail(routineId) }) }); }
export function useReorderRoutineDays(routineId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (orderedIds: string[]) => reorderRoutineDays(routineId, orderedIds), onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.detail(routineId) }) }); }
export function useRenameRoutine(routineId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (name: string) => renameRoutine(routineId, name), onSuccess: () => Promise.all([client.invalidateQueries({ queryKey: routineKeys.all }), client.invalidateQueries({ queryKey: routineKeys.detail(routineId) }), client.invalidateQueries({ queryKey: ['today'] })]) }); }
export function useRenameRoutineDay(routineId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ dayId, name }: { dayId: string; name: string }) => renameRoutineDay(dayId, name), onSuccess: () => client.invalidateQueries({ queryKey: routineKeys.detail(routineId) }) }); }
